path.wd <- "/home/schmingo/Diplomarbeit/src/satellite/MOD02_2013-07-07/"
setwd (path.wd)

file.rename(from, to)
file.rename(band_EV_1KM_Emissive_b0.tif, B01)
file.rename(band_EV_1KM_Emissive_b1.tif)
file.rename(band_EV_1KM_Emissive_b2.tif)
file.rename(band_EV_1KM_Emissive_b3.tif)
file.rename(band_EV_1KM_Emissive_b4.tif)
file.rename(band_EV_1KM_Emissive_b5.tif)
file.rename(band_EV_1KM_Emissive_b6.tif)
file.rename(band_EV_1KM_Emissive_b7.tif)
file.rename(band_EV_1KM_Emissive_b8.tif)
file.rename(band_EV_1KM_Emissive_b9.tif)
file.rename(band_EV_1KM_Emissive_b10.tif)
file.rename(band_EV_1KM_Emissive_b11.tif)
file.rename(band_EV_1KM_Emissive_b12.tif)
file.rename(band_EV_1KM_Emissive_b13.tif)
file.rename(band_EV_1KM_Emissive_b14.tif)
file.rename(band_EV_1KM_Emissive_b15.tif)
